### PR TITLE
WIP: Add unit tests

### PR DESCRIPTION
**Pull request by cfarm**
Adds gulp build tooling + basic unit tests for the `process-csv` script. More documentation coming
 
## Additions

- gulp tasks
- capital framework CSS, for use in the charts demo pages for design accuracy
- unit tests for process-csv
- build pages and run tests with gulp in Travis CI

## Removals

-

## Changes

- update process-csv to export functions for unit tests

## Testing

- check out branch
- run `./setup.sh`
- run `gulp watch` to spin up local server and view sample charts page
- run `gulp test` to run unit tests. 1 is failing, because 🐞  BUG 🐞 

## Review

- @mistergone 
- @marteki 
- @hillaryj 

[Preview this PR without the whitespace changes](?w=0)

## Notes

-

## Todos

-

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by mistergone** [comment]
There's a missing comma in `LineChart.js` that's causing an error:

Line 196, Column 6: `gridLineColor: '#d2d3d5'`

Adding a comma at the end of that line and running gulp again remedied it, so that's an easy fix. :)

**Comment by mistergone** [comment]
`gulp test` gave me some linting errors and 1 test error (as expected, right?)

So, aside from the missing comma, thumbs up!

👍

**Comment by cfarm** [comment]
fixed the missing commas!

lint warnings + 1 failing test are expected, yes!

**Comment by cfarm** [comment]
i'm still fixing up sauce labs browser-tests with this branch, so this isn't ready for merge yet.

**Comment by cfarm** [comment]
closing in favor of #40 which is on upstream

**Pull request closed without merging**
