### PR TITLE
Add three new colors for line charts

### PR DESCRIPTION
**Pull request by marteki**
Add `dark-gold`, `neutral`, and `purple` from Capital Framework as new colors for line charts

In order to add all three colors, we also needed to update our version of `cf-core`.

## Additions

- Add three new color schemes as options for line charts
- Add new charts with this color to the demo page (using placeholder data)

## Changes
- Upgraded `cf-core` dependency to `4.7.0`

## Testing

1. Run `/.setup.sh` which should be successful (with existing webpack warnings).
2. Run `gulp watch` to view the demo page. Three new line charts should be at the top of the page, in the three new colors but using the auto loan origination data.

## Screenshots

screen shot 2018-08-17 at 4 01 53 pm

screen shot 2018-08-17 at 4 02 01 pm

screen shot 2018-08-17 at 4 02 13 pm

## Notes

I didn't see the notification that the contributing guidelines had changed until after I opened this PR, so it's not coming from a fork. Mea culpa.

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by anselmbradford** [comment]
This works, but it seems like we should be using the highcharts color API to set colors https://api.highcharts.com/highcharts/colors
we don't want our CSS hooked into the highcharts classes. There's no guarantee highchart devs won't change those in the future.
The colors [set in the markup](https://github.com/cfpb/cfpb-chart-builder/blob/master/src/js/index.js#L105) are passed in the `props` [here](https://github.com/cfpb/cfpb-chart-builder/blob/master/src/js/charts/LineChart.js#L79), which can be passed to highcharts in that function.

**Comment by marteki** [comment]
@anselmbradford Nice find! In the interest of scope, let's stick with the current implementation to get this in placement for our delivery deadline. I'll add an issue to our internal repo to track it as an improvement.

**Comment by anselmbradford** [comment]
> Nice find! In the interest of scope, let's stick with the current implementation to get this in placement for our delivery deadline. I'll add an issue to our internal repo to track it as an improvement.

Ehhh we really shouldn't be dipping inside the implementation of third-party libraries, that's why they have an API. What is our deadline for these colors? Sept 30?

**Comment by marteki** [comment]
@anselmbradford Our committed-to deadline for getting these colors up using the existing implementation and available for dev/UX use and product owner review is the end of this sprint, COB Tuesday, Aug 21st (AKA tomorrow). We can talk about the overall project deadlines and priorities at scrum today.

**Comment by anselmbradford** [comment]
cf-core has been updated to 4.10.0 and could be updated here.

**Comment by marteki** [comment]
Cool, I updated `cf-core` as recommended. Merging now.

**Pull request merged**
