### PR TITLE
Update dependencies, including highcharts 7.1.2

### PR DESCRIPTION
**Pull request by anselmbradford**
Updates outdates dependencies and fixes deprecated code structures:
- Webpack recommends if the usebuiltins attribute is set that the version of corejs be set also and core-js be added as a dependency.
- Jest does not allow tests that return a value, so this was removed from the get-data test.
- The syntax for the highcharts accessibility features was deprecated, so this PR updates it. 

## Additions

- Explicitly adds `core-js` per webpack recommendations.

## Changes

- Updates to latest `gulp`, `browser-sync`, `webpack`, `webpack-stream`, `cf-core`, `cf-layout`, `cf-typography`, `babel`, `autoprefixer`, `babel-jest`, `babel-loader`, `del`, `gulp-header`, `gulp-sourcemaps`, `jest`, `sauce-connect-launcher`, and`through2`.
- Replaces deprecated `series.exposeElementToA11y` with `series.accessibility.exposeAsGroupOnly`.
- Replaces deprecated `series.skipKeyboardNavigation` with `series.accessibility. keyboardNavigation.enabled`.
- Minor code formatting and code comments added to demo.js.
- Moves hidden `.babelrc` to visible `babel.config.js`.
- Sets node target in babel config to fix error thrown when tests were run (solution pulled from https://github.com/babel/babel/issues/5085)
- Replace `uglifyjs-webpack-plugin` with `terser-webpack-plugin`.
- Use EventObserver to dispatch events to properly resolve/reject Promises returned from update method.
- Refactor map/chart demo to have clickable buttons for testing each state.

## Testing

- Run `./setup.sh && gulp build && gulp watch` and the demo page should work as before, where applicable. New map buttons should be clickable to toggle between different layers. There is also an updatable chart.
- `npm test` should pass.

Screen Shot 2019-07-30 at 11 00 41 AM

Screen Shot 2019-07-30 at 11 00 51 AM

Testing in cfgov-refresh should be done with https://github.com/cfpb/cfgov-refresh/pull/4942, which is the corresponding highcharts version update. The `cfpb-chart-builder` repo can be copied into the `node_modules` folder in cfgov-refresh.

## Notes

- ~~The geomap fails with `Uncaught TypeError: Cannot read property 'select' of undefined` sometimes, which is a known issue.~~
- @contolini may be best to test the accessibility changes, as I'm not totally certain how they are expected to work (https://github.com/cfpb/cfpb-chart-builder/pull/78 for reference).

### CODE REVIEW

**Comment by cfarm** [comment]
Reviewing this now

**Comment by cfarm** [comment]
I am seeing the geographic map fail completely on the first update call, the data doesn't load and the map disappears. Paging @contolini to review this for that specific chart.

**Comment by cfarm** [comment]
The y axis is too tall on the bar charts:

| master branch | this branch |
|---------------|-------------|
|         Screen Shot 2019-04-25 at 1 34 24 PM      |          Screen Shot 2019-04-25 at 1 34 22 PM   |

**Comment by cfarm** [comment]
Line charts too:

| master branch | this branch |
|---------------|-------------|
|    Screen Shot 2019-04-25 at 1 42 41 PM   |        Screen Shot 2019-04-25 at 1 42 39 PM   |

**Comment by cfarm** [comment]
On narrow screen sizes, the "Value after __date___ are projected" label is completely gone on Bar, Line and LineIndex charts:




| master branch | this branch |
|---------------|-------------|
|       Screen Shot 2019-04-25 at 1 53 12 PM        |       Screen Shot 2019-04-25 at 1 53 17 PM      |

And on Line and LineIndex charts, the Legend and the Y-axis labels are overlapping and not legible:


| master branch | this branch |
|---------------|-------------|
|        Screen Shot 2019-04-25 at 1 56 34 PM       |      Screen Shot 2019-04-25 at 1 56 13 PM       |

**Comment by anselmbradford** [comment]
> Layout bugs on the Line, Bar and LineIndex charts and the

@cfarm pushed up an update for the layout issues. Differences (in my opinion acceptable) are:
 - Tilemap tile text moved up (which actually better centers it).
 - Some line charts top and bottom ranges are narrower making the line fit better in the area.
 - The line comparison labels moved up (which actually better centers it).

> Geographic map update function no longer works.

I was told this was a known issue. It's intermittent, if it's the same issue as in the notes in the original post.

**Comment by contolini** [comment]
It appears versions [7.1.0](https://www.highcharts.com/blog/changelog/#highcharts-v7.1.0) and later break the `update` method. It works with version 7.0.3 and lower. Stay tuned while I investigate.

**Comment by contolini** [comment]
Yup, it's a reported regression: https://github.com/highcharts/highcharts/issues/10617

I'd hold this PR until 7.1.2 is released with a fix.

**Comment by cfarm** [comment]
> @contolini may be best to test the accessibility changes, as I'm not totally certain how they are expected to work (#78 for reference).

Looks like from that PR the borders on the map should be black. They are gray for me on this branch:

Screen Shot 2019-08-02 at 5 06 20 PM

**Comment by cfarm** [comment]
Also the tooltips text should be black: 
Screen Shot 2019-08-02 at 5 07 14 PM

**Comment by anselmbradford** [comment]
@cfarm The actual colors are set by the page implementing chart-builder. I've push up the black borders, but note that this is only for the demo. The actual place it's used on the site has black borders and gray tooltip text, regardless of the demo colors. However, it would be nice to have them aligned.

To test:
 1. Copy `cfpb-chart-builder` repo into `cfgov-refresh` `node_modules` (or npm link)
 2. Checkout https://github.com/cfpb/cfgov-refresh/pull/4942 and run a server.
 3. See map http://localhost:8000/data-research/mortgage-performance-trends/mortgages-90-or-more-days-delinquent/
 4. Compare to https://www.consumerfinance.gov/data-research/mortgage-performance-trends/mortgages-90-or-more-days-delinquent/

Screen Shot 2019-08-02 at 6 47 04 PM

**Pull request merged**
