### PR TITLE
Clean up dependencies

### PR DESCRIPTION
**Pull request by anselmbradford**
Project apparently contains large numbers of unused and in one case a redundant dependency (`babel-preset-env` in both deps and dev-deps).

I removed dependencies I couldn't find in a file search in the project. Let me know if there's a setup here where that wouldn't show a dependency.

`fs` is built-into node as far as I know and can just be required without needing to be in package.json.

`ecstatic` has a security vulnerability and is a dep of `http-server`, which did not appear to be used.

screen shot 2017-12-29 at 11 07 46 am

## Removals

- `es6-promise`, `html5shiv`, `browserify`, `fs`, `gulp-concat`, `http-server`, `jquery`, `less-plugin-clean-css`, `nock`, `uglify-js`, `uglifyify`, `watchify`

## Changes

- Re-generate `package-lock.json`

## Testing

- `npm install`
- `./setup.sh && npm run build && npm run test` should pass.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@marteki Can you do me a favor and run `npm -v` and `node -v`. If node is less than 8 please upgrade it. Then throw out `node_modules` and run `npm install` and then `./setup.sh && npm run build && npm run test`

**Comment by marteki** [comment]
```
~/Repositories/cfpb/cfpb-chart-builder cleanup_deps* 👾  npm -v
5.6.0
~/Repositories/cfpb/cfpb-chart-builder cleanup_deps* 👾  node -v
v8.4.0
```

Following the other instructions now.

**Comment by anselmbradford** [comment]
@marteki When you re-generated `package-lock.json`, were there any changes to the `package-lock.json` in this PR?

**Comment by marteki** [comment]
@ans 

No, the generated file has no difference from the PR! It changed the versions I had loaded locally for `babel-core` to 6.26.0, `babel-loader` to 7.1.2, `babel-preset-env` to 1.6.1, and removed `babel-preset-es2015`. All of which I _should_ have already had, as [it's in the PR file](https://github.com/cfpb/cfpb-chart-builder/blob/35940498cc6bd4f8fd93e6df027a25926406ce50/package-lock.json).

For some reason, it didn't automatically replace it.

**Comment by anselmbradford** [comment]
@marteki 

Okay, cool! Is it good to merge this or would you like someone else to check beforehand?

**Pull request merged**
