### PR TITLE
Updates to gulp 4

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Updates project to use gulp 4

## Testing

- `npm install`
- gulp tasks should pass:
  - `gulp`
  - `gulp build`
  - `gulp browsersync`
  - `gulp clean`
  - `gulp connect`
  - `gulp lint`
  - `gulp scripts`
  - `gulp styles`
  - `gulp test`
  - `gulp watch`

### CODE REVIEW

**Comment by anselmbradford** [comment]
You're sure `watch` worked before?

**Comment by contolini** [comment]
Yeah it works on master. I updated the watch task and I'll push it up shortly.

Unrelated: files.cf.gov is now HTTPS-only which is causing some tests to fail. A fix for that is coming shortly.

**Comment by contolini** [comment]
@anselmbradford I merged in my other branch I was working on because it had the aforementioned fixes.

When you have a sec pull down this branch and `gulp build && npm test` and verify that the Sauce Lab browser tests pass.

**Comment by anselmbradford** [comment]
> When you have a sec pull down this branch and gulp build && npm test and verify that the Sauce Labs browser tests pass.

I still run into https://github.com/cfpb/cfpb-chart-builder/issues/91

**Pull request merged**
