### PR TITLE
Refactor project file structure

### PR DESCRIPTION
**Pull request by contolini**
There are a lot of minute gulp task changes here but the crux is that I moved `/src/index.html` to `/test/index.html` because the HTML file is not a part of this project's source code, we just use it for testing purposes.

## Additions

- Lockfile for npm 5.

## Removals

- 

## Changes

- Moved `index.html` from /src to /test.
- Updated all gulp tasks to accommodate the above change.
- Changed the gulp tasks to only output `cfpb-chart-builder.css` and `cfpb-chart-builder.js` to `/dist` (and not index.html with nested directories for the CSS/JS).

## Testing

- `nvm use 8`
- `./setup.sh` to build everything
- `npm test` to verify tests still pass as normal (you'll need to add [sauce credentials](https://github.com/cfpb/cfpb-chart-builder#testing) if you haven't already
- `gulp watch` to verify the demo page still loads all the charts

To verify the charts still load correctly in cfgov-refresh:

- `nvm use 8`
- `npm link`
- `cd ~/wherever/your/projects/are/cfgov-refresh/`
- `npm link cfpb-chart-builder`
- `gulp build`
- `./runserver`
- Navigate to http://127.0.0.1:8000/data-research/consumer-credit-trends/credit-cards/borrower-risk-profiles/

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by cfarm** [comment]
Demo + local tests work. The Sauce lab videos show no charts loaded though - you might want to look into that.

Testing in `cfgov-refresh` now

**Comment by contolini** [comment]
> The Sauce lab videos show no charts loaded though - you might want to look into that.

Hmmm I wonder if test-runner.js needs to be tweaked. I'll check it out.

**Comment by cfarm** [comment]
The CSS wouldn't compile properly during `gulp build` in `cfgov-refresh` for me without editing that repo's gulp config, line 68, to account for the new file structure:

```
        paths.modules + '/cfpb-chart-builder/src/css',
```

The on-demand JS is also erroring probably for a similar reason that I need to look into after Dev CoP:

```
ERROR in ./cfgov/unprocessed/js/routes/on-demand/chart.js
Module not found: Error: Can't resolve 'cfpb-chart-builder' in '/Users/farmanc/Sites/cfgov-refresh/cfgov/unprocessed/js/routes/on-demand'
 @ ./cfgov/unprocessed/js/routes/on-demand/chart.js 9:0-29
```

**Comment by cfarm** [comment]
@contolini if you can fix those issues in cfgov-refresh, it's probably a good idea to put them on a WIP PR branch there for those of us testing this branch, since those updates will have to get in there eventually anyway

**Comment by contolini** [comment]
@cfarm Cool I'll dig into the cfgov-refresh issues.

**Comment by mistergone** [comment]
Everything worked for me, including `cfgov-refresh`

Should there be a mention in the `README` about using node 8, or any other documentation changes?

**Comment by contolini** [comment]
> Should there be a mention in the README about using node 8, or any other documentation changes?

Yes, definitely. The README could use some attention (we never even filled out the configuration section). I'd like to update all documentation in a future PR once the dust on this one has settled.

**Comment by contolini** [comment]
@cfarm Sauce is back in business https://saucelabs.com/beta/tests/77b20121ba22466db1c1ff9ec0525d0c/watch

**Comment by mistergone** [comment]
> > Should there be a mention in the README about using node 8, or any other documentation changes?
>
> Yes, definitely. The README could use some attention (we never even filled out the configuration section). I'd like to update all documentation in a future PR once the dust on this one has settled.

Yeah, I will take partial responsibility for this problem myself. :)

**Comment by cfarm** [comment]
> @cfarm Sauce is back in business https://saucelabs.com/beta/tests/77b20121ba22466db1c1ff9ec0525d0c/watch

:cowboy_hat_face: yeehaw!

**Comment by contolini** [comment]
Alrighty https://github.com/cfpb/cfgov-refresh/pull/3222 will allow cfgov-refresh to seamlessly import both the old file structure and the new one.

Thanks for the reviews everyone! @cfarm when you have a sec make the minor change that's in the above PR and see if running `gulp styles` in cfgov-refresh starts working.

**Pull request merged**
