### PR TITLE
Updates to ESLint 4

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Updates `gulp-eslint` from `3.0.1` to `4.0.0`.
- Auto-fixes linting errors.
- changes `npm run lint` script to refer to `gulp lint` to remove need for extra eslint dep in package.json.

## Testing

- `./setup.sh && gulp build`
- `gulp lint` should show only warning.
- `gulp test` should pass.

### CODE REVIEW

**Comment by anselmbradford** [comment]
bwhamp

**Comment by anselmbradford** [comment]
stale

**Comment by sebworks** [comment]
This looks good on my end but you will need to run in through babel on cfgov-refresh to ensure it works as expected.

**Comment by anselmbradford** [comment]
To test I copied the /src/ files from this PR into cfgov-refresh node_modules/cfpb-chart-builder and ran `gulp build` in cfgov-refresh and visited http://localhost:8000/data-research/mortgage-performance-trends/mortgages-90-or-more-days-delinquent/

**Pull request merged**
