### PR TITLE
Removes watch | update eslint

### PR DESCRIPTION
**Pull request by anselmbradford**
Remove `browsersync` to align with cfgov-refresh config and update to ESLint 5.

## Additions

- Add linting to Travis config.

## Removals

- Remove `browsersync` to align with cfgov-refresh config.

## Changes

- Updates config to ESLint 5.

## Testing

- `./setup.sh` should pass.
- `gulp lint` should pass.

### CODE REVIEW

**Comment by cfarm** [comment]
Looks good and works, but is there a reason to remove browsersync aside from "to align with cfgov-refresh config?" I missed that when that changed happened in cfgov-refresh.

**Comment by anselmbradford** [comment]
> Looks good and works, but is there a reason to remove browsersync aside from "to align with cfgov-refresh config?" I missed that when that changed happened in cfgov-refresh.

It was removed in cfgov-refresh because it was added to production but not run there, has some security vulnerabilities [reported by snyk](https://snyk.io/test/npm/browser-sync), and had low usage among the team actively working in cfgov-refresh at the time. Is it something you use here? I removed it here as it's easier from a maintenance perspective if the build config across repos is the same.

**Comment by cfarm** [comment]
> It was removed in cfgov-refresh because it was added to production but not run there, has some security vulnerabilities reported by snyk, and had low usage among the team actively working in cfgov-refresh at the time. 

The second reason is compelling and makes a ton of sense, but I disagree with the last reason. I would still find it useful to have the watch functionality in cfgov-refresh, rather than having to re-run `gulp build` manually.

> Is it something you use here?

Yes, this task was used heavily during development of the graphs. We will probably find it useful while we are adding the new graphs and data. Is there a way we can remove the browsersync dependency (assuming there's still a vulnerability) but still have a watch task that does what we need (compiles on save)? If so that would also be fantastic to contribute back to cfgov-refresh.

**Comment by anselmbradford** [comment]
Okay, I've opened https://github.com/cfpb/cfpb-chart-builder/pull/104 for just the ESLint 5 update part of this.

As far as I know gulp watch and browsersync are separate entities, so we could probably have the watch without browsersync.

**Comment by cfarm** [comment]
Perfect, keeping `gulp watch` is actually pretty necessary: that's how you can run the server for the demo site!

**Pull request closed without merging**
